#!/usr/bin/env python3

#print("Welcome to python scripting.")
#print("This lecture is about printing special characters.")
#print("Welcome to python scripting.\nThis lecture is about special characters in print statement.")
#print("Hello""Inder")
#print('Hello Inder.\nHow are you?')
#print("Hello \bInder.")
#print("Hello \b\bInder.")
#print("Hello \b Inder.")
#print("Hello \b\b Inder")
#print("Hello \tworld.")
#print("Hello\tworld.")
#print("Hello \t world.")
#print("Hello  \tworld.")
#print("Python's class.")
#print('Python's class.')
#print('Python\'s class.')
#print("This is "python" class.")
#print("This is \"python\" class.")
#print("D:\\Users\\Inderpal\\Downloads")
print("ALERT\a")
